package com.jssdvv.ara.core.domain.model

data class Motor(
    val motorId: Int,
    val machineId: Int,
    val brand: String?,
    val model: String?,
    val serialNumber: String?,
    val fabricator: String?,
    val supplier: String?,
    val price: Float?,
    val acquisitionDate: Int?,
    val weight: Float?,
    val weightUnit: String?,
    val frequency: Float?,
    val frequencyUnit: String?,
    val rpm: Int?,
    val eff: Float?,
    val sf: Float?,
    val power: Float?,
    val powerUnit: String?,
    val voltageMax: Float?,
    val voltageMin: Float?,
    val voltageUnit: String?,
    val currentMax: Float?,
    val currentMin: Float?,
    val currentUnit: String?,
    val pf: Float?,
    val ph: Int?,
    val cosPhi: Float?,
    val amb: Float?,
    val ambUnit: String?,
    val fr: String?,
    val duty: String?
)